// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoGRhb4TnUnjsH7ZiE8oj-C8dhUz8iwZs',
    appId: '1:1031946659785:web:d70cf9c46fae55010e6a18',
    messagingSenderId: '1031946659785',
    projectId: 'drinks-b5f44',
    authDomain: 'drinks-b5f44.firebaseapp.com',
    storageBucket: 'drinks-b5f44.appspot.com',
    measurementId: 'G-5Z2V760TWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkF5I3m7daH26PbrXOciwFQR6_dfAjsMo',
    appId: '1:1031946659785:android:8eb13c1e06d99d500e6a18',
    messagingSenderId: '1031946659785',
    projectId: 'drinks-b5f44',
    storageBucket: 'drinks-b5f44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe_p2y_2Hr9FDPXBZo3UbGGdqFHkrRrh8',
    appId: '1:1031946659785:ios:ce7844456c4478f00e6a18',
    messagingSenderId: '1031946659785',
    projectId: 'drinks-b5f44',
    storageBucket: 'drinks-b5f44.appspot.com',
    androidClientId: '1031946659785-h2jor7uela7k80n5clm0kp76a3bk58ua.apps.googleusercontent.com',
    iosClientId: '1031946659785-b5o5sh7umtrec2v2ra18qo6ut6edog6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.winedrinks',
  );

}